[theme]
base = "light"
primaryColor = "#0B1633"
backgroundColor = "#F6F7FB"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1B2440"

[client]
toolbarMode = "minimal"
showErrorDetails = false

[browser]
gatherUsageStats = false
